sudo: required
services: docker
language: python
install:
  - pip install docker molecule openshift
  # Temporary, need to get this PR merged
  - pip install -U https://github.com/fabianvf/molecule/archive/molecule-docker-cmd.tar.gz
script:
  - cookiecutter . --config-file test/role.yaml --no-input
  - cd role && molecule test --all
  - cookiecutter . --config-file test/playbook.yaml --no-input
  - cd playbook && molecule test --all
