sudo: required
services: docker
language: python
install:
  - pip install docker molecule openshift
  # Temporary, need to get this PR merged
  - pip install -U git+https://github.com/fabianvf/molecule.git@molecule-docker-cmd
script:
  - cookiecutter . --config-file test/role.yaml --no-input
  - (cd role-test && molecule test -s default && molecule test -s test-local)
  - cookiecutter . --config-file test/playbook.yaml --no-input
  - (cd playbook-test && molecule test -s default && molecule test -s test-local)
