---
- name: Converge
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: '{{ "{{ ansible_playbook_python }}" }}'
    namespace: osdk-test
    deploy_dir: '{{"{{ playbook_dir }}/../../../../deploy"}}'
    image_name: {{ cookiecutter.group }}/{{cookiecutter.app_name }}:testing
  tasks:
  # TODO: Would love to figure out how to build the operator in the doc
  - name: Build the Operator
    debug: msg=TODO

  - name: Create the Operator Deployment
    k8s:
      namespace: '{{ '{{ namespace }}' }}'
      definition: "{{'{{'}} lookup('template', '/'.join([deploy_dir, 'operator.yaml'])) {{'}}'}}"
    vars:
      pull_policy: Never
      REPLACE_IMAGE: '{{ '{{ image_name }}' }}'

  - name: Create the {{ cookiecutter.group }}/{{ cookiecutter.version }}.{{ cookiecutter.kind }}
    k8s:
      namespace: '{{ '{{ namespace }}' }}'
      definition: "{{'{{'}} lookup('file', '/'.join([deploy_dir, 'crds/{{cookiecutter.group.split('.')[0]}}_{{cookiecutter.version}}_{{cookiecutter.kind|lower}}_cr.yaml'])) {{'}}'}}"

  - name: Get the newly created Custom Resource
    debug:
      msg: "{{'{{'}} lookup('k8s', group='{{cookiecutter.group}}', api_version='{{cookiecutter.version}}', kind='{{cookiecutter.kind}}', namespace=namespace, resource_name=cr.metadata.name) {{'}}'}}"
    vars:
      cr: "{{'{{'}} lookup('file', '/'.join([deploy_dir, 'crds/{{cookiecutter.group.split('.')[0]}}_{{cookiecutter.version}}_{{cookiecutter.kind|lower}}_cr.yaml'])) | from_yaml {{'}}'}}"
