kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ cookiecutter.app_name }}
subjects:
- kind: ServiceAccount
  name: {{ cookiecutter.app_name }}
roleRef:
  kind: Role
  name: {{ cookiecutter.app_name }}
  apiGroup: rbac.authorization.k8s.io
