---

- name: Build Operator in Kubernetes docker container
  hosts: k8s
  vars:
    image_name: {{ cookiecutter.group }}/{{cookiecutter.app_name }}:testing
  tasks:
  # using command so we don't need to install any dependencies
  - name: Get existing image hash
    command: docker images -q {{'{{image_name}}'}}
    register: prev_hash
    changed_when: false

  - name: Build Operator Image
    command: docker build -f /build/build/Dockerfile -t {{'{{ image_name }}'}} /build
    register: build_cmd
    changed_when: not prev_hash.stdout or (prev_hash.stdout and prev_hash.stdout not in ''.join(build_cmd.stdout_lines[-2:]))

- name: Converge
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: '{{ "{{ ansible_playbook_python }}" }}'
    namespace: osdk-test
    deploy_dir: '{{'{{ lookup("env", "MOLECULE_PROJECT_DIRECTORY") }}/deploy'}}'
    image_name: {{ cookiecutter.group }}/{{cookiecutter.app_name }}:testing
  tasks:

  - name: Create the Operator Deployment
    k8s:
      namespace: '{{ '{{ namespace }}' }}'
      definition: "{{'{{'}} lookup('template', '/'.join([deploy_dir, 'operator.yaml'])) {{'}}'}}"
    vars:
      pull_policy: Never
      REPLACE_IMAGE: '{{ '{{ image_name }}' }}'

  - name: Create the {{ cookiecutter.group }}/{{ cookiecutter.version }}.{{ cookiecutter.kind }}
    k8s:
      namespace: '{{ '{{ namespace }}' }}'
      definition: "{{'{{'}} lookup('file', '/'.join([deploy_dir, 'crds/{{cookiecutter.group.split('.')[0]}}_{{cookiecutter.version}}_{{cookiecutter.kind|lower}}_cr.yaml'])) {{'}}'}}"

  - name: Get the newly created Custom Resource
    debug:
      msg: "{{'{{'}} lookup('k8s', group='{{cookiecutter.group}}', api_version='{{cookiecutter.version}}', kind='{{cookiecutter.kind}}', namespace=namespace, resource_name=cr.metadata.name) {{'}}'}}"
    vars:
      cr: "{{'{{'}} lookup('file', '/'.join([deploy_dir, 'crds/{{cookiecutter.group.split('.')[0]}}_{{cookiecutter.version}}_{{cookiecutter.kind|lower}}_cr.yaml'])) | from_yaml {{'}}'}}"

- import_playbook: '{{'{{ playbook_dir }}/../default/asserts.yml'}}'
