---
- name: Converge
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: '{{ "{{ ansible_playbook_python }}" }}'
  roles:
    - {{ cookiecutter.kind | lower }}
  post_tasks:
    # Verify that cluster state is as desired
    - assert:
        that: yes
