---
{% if cookiecutter.generate_playbook == 'yes'  -%}
- import_playbook: '{{'{{ playbook_dir }}/../../playbook.yml'}}'
{% endif -%}

  {% if cookiecutter.generate_playbook == 'no'  -%}
- name: Converge
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: '{{ "{{ ansible_playbook_python }}" }}'
  roles:
    - {{ cookiecutter.kind | lower }}
  {% endif -%}

- import_playbook: '{{'{{ playbook_dir }}/asserts.yml'}}'
